### ISSUE TITLE
大佬怎么用啊，有没有使用教程有没有群聊，求

### ISSUE THREAD

**Issue by ni-feng-le** [0-8-4/miui-auto-tasks#105]

**Comment by TardisXE** [comment]
使用方法请仔细阅读Readme及[项目的Wiki](https://github.com/0-8-4/miui-auto-tasks/wiki)，本项目没有官方的群聊或其他交流平台，亦不提供付费支持

**Comment by ni-feng-le** [comment]
> 使用方法请仔细阅读Readme及[项目的Wiki](https://github.com/0-8-4/miui-auto-tasks/wiki)，本项目没有官方的群聊或其他交流平台，亦不提供付费支持

能不能用青龙，我就会一个青龙，给个青龙命令，仅仅用小米社区签到

**Comment by ni-feng-le** [comment]
> 使用方法请仔细阅读Readme及[项目的Wiki](https://github.com/0-8-4/miui-auto-tasks/wiki)，本项目没有官方的群聊或其他交流平台，亦不提供付费支持

为啥不给个群聊啊

**Comment by klcb2010** [comment]
> > 使用方法请仔细阅读Readme及[项目的Wiki](https://github.com/0-8-4/miui-auto-tasks/wiki)，本项目没有官方的群聊或其他交流平台，亦不提供付费支持
> 
> 能不能用青龙，我就会一个青龙，给个青龙命令，仅仅用小米社区签到

仔细看文档说明  有青龙的使用教程

**Comment by TardisXE** [comment]
建议在[github的讨论区](https://github.com/0-8-4/miui-auto-tasks/discussions)讨论，后续我们会考虑为wiki添加更详细的部署说明

**Comment by 0-8-4** [comment]
refer to #72 (手动狗头

**Comment by ni-feng-le** [comment]
看一下这个日志，用的小米社区网页版cookie除了这个没其他的了，我这里运行了我去APP看还是没有签到，求解答


MIUI-Auto-Task
## 开始执行... 2023-12-07 17:43:02

[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m13[0m - [1mMIUI-AUTO-TASK v1.7.3[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m14[0m - [1m---------- 系统信息 -------------[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m25[0m - [1m操作系统平台: Linux-3.10.0-1160.el7.x86_64-x86_64-with[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m26[0m - [1m操作系统版本: #1 SMP Mon Oct 19 16:18:59 UTC 2020[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m27[0m - [1m操作系统名称: Linux[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m28[0m - [1m操作系统位元: ('64bit', '')[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m29[0m - [1m操作系统类型: x86_64[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m30[0m - [1m处理器信息: [0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m31[0m - [1mPython 版本: 3.10.11 ('main', 'May 11 2023 23:39:48')[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m16[0m - [1m---------- 项目信息 -------------[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m17[0m - [1m这是一个免费且开源的项目，如果你是付费购买获得请务必退款[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m18[0m - [1m项目地址：https://github.com/0-8-4/miui-auto-tasks[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m19[0m - [1m欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m20[0m - [1m---------- 脚本日志 -------------[0m
[32m17:43:04[0m - [1mINFO [0m | [36mlogin[0m.[36mlogin[0m:[36m84[0m - [1mCookie有效，跳过登录[0m
[32m17:43:04[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m33[0m - [1m开始执行抢先体验小米澎湃OS！任务[0m
[32m17:43:04[0m - [31m[1mERROR[0m | [36mmiuitask[0m.[36mmain[0m:[36m41[0m - [31m[1m未找到抢先体验小米澎湃OS！任务[0m
[32m17:43:04[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m33[0m - [1m开始执行每日签到任务[0m
Traceback (most recent call last):
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 48, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 36, in main
    token = await get_token(cookies["cUserId"]) if task_obj == CheckIn else None
KeyError: 'cUserId'


## 执行结束... 2023-12-07 17:43:04  耗时 2 秒

**Comment by klcb2010** [comment]
别填cookie 账号密码正确就会自动生成

**Comment by ni-feng-le** [comment]
> 别填cookie 账号密码正确就会自动生成
不填cookie他会说账号密码登录成功cookie获取失败，然后也是没下文了
