### ISSUE TITLE
[求助] 读取数据文件失败

### ISSUE THREAD

**Issue by dan3577** [0-8-4/miui-auto-tasks#146]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.0

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.12

### Describe the Bug

2023-11-14 08:57:48.957 | ERROR    | utils.config:load_config:131 - 读取数据文件失败，请检查数据文件 /ql/data/scripts/asmrlt2_miui-auto-tasks_master/data/config.yaml 格式是否正确

config.yaml格式复制wiki提供的数据，仅修改ID和password内容，，config.yaml权限777了

### MIUITask Log

2023-11-14 09:03:22.659 | ERROR    | utils.config:load_config:131 - 读取数据文件失败，请检查数据文件 /ql/data/scripts/asmrlt2_miui-auto-tasks_master/data/config.yaml 格式是否正确
Traceback (most recent call last):

  File "/ql/data/scripts/asmrlt2_miui-auto-tasks_master/miuitask.py", line 8, in <module>
    from utils.api.login import Login

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/ql/data/scripts/asmrlt2_miui-auto-tasks_master/utils/api/login.py", line 10, in <module>
    from ..config import Account, write_plugin_data

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/ql/data/scripts/asmrlt2_miui-auto-tasks_master/utils/config.py", line 148, in <module>
    ConfigManager.load_config()
    │             └ <classmethod(<function ConfigManager.load_config at 0x7fb50140fb50>)>
    └ <class 'utils.config.ConfigManager'>

> File "/ql/data/scripts/asmrlt2_miui-auto-tasks_master/utils/config.py", line 126, in load_config
    new_model = Config.model_validate(data)
                │      │              └ {'accounts': [{'uid': 127xxxxxxx, 'password': 'xxxxxxxxx', 'user-agent': 'Mozilla/5.0 (Android 11; Mobile; rv:95.0) Gecko/95...
                │      └ <classmethod(<function BaseModel.model_validate at 0x7fb501cd7640>)>
                └ <class 'utils.config.Config'>

  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
           │   │                      └ <method 'validate_python' of 'pydantic_core._pydantic_core.SchemaValidator' objects>
           │   └ SchemaValidator(title="Config", validator=Model(
           │         ModelValidator {
           │             revalidate: Never,
           │             validator: ModelFiel...
           └ <class 'utils.config.Config'>

pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
accounts.0.uid
  Input should be a valid string [type=string_type, input_value=127xxxxxxx, input_type=int]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
Traceback (most recent call last):
  File "/ql/data/scripts/asmrlt2_miui-auto-tasks_master/miuitask.py", line 8, in <module>
    from utils.api.login import Login
  File "/ql/data/scripts/asmrlt2_miui-auto-tasks_master/utils/api/login.py", line 10, in <module>
    from ..config import Account, write_plugin_data
  File "/ql/data/scripts/asmrlt2_miui-auto-tasks_master/utils/config.py", line 148, in <module>
    ConfigManager.load_config()
  File "/ql/data/scripts/asmrlt2_miui-auto-tasks_master/utils/config.py", line 126, in load_config
    new_model = Config.model_validate(data)
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
accounts.0.uid
  Input should be a valid string [type=string_type, input_value=127xxxxxxx, input_type=int]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type

### MIUITask Config

```shell
accounts:
  - uid: 127xxxxxx
    password: xxxxxxxx
    user-agent: 'Mozilla/5.0 (Android 11; Mobile; rv:95.0) Gecko/95.0 Firefox/95.0'
    check-in: true
    browse-user-page: true
    browse-post: true
    thumb-up: false
    browse-specialpage: true
    board-follow: false
    carrot-pull: true
logging: true
version: v1.7.0
```

### Screenshots

![image](https://github.com/0-8-4/miui-auto-tasks/assets/52194615/f4d1ddc1-a996-479c-ba58-802583297fb3)

**Comment by Night-stars-1** [comment]
wiki内容过时，请删除config运行一次程序，自动生成

**Comment by 0-8-4** [comment]
删除你现在的配置文件，先运行一遍程序，会自动生成一个配置文件模版

**Comment by Tianqiwangdie** [comment]
请问青龙面板订阅管理中，拉取脚本，但在脚本管理当中并没有config.yaml文件，我需要怎么做
![image](https://github.com/0-8-4/miui-auto-tasks/assets/120441658/4e7bcceb-fd01-4f5a-a9a4-57c4c5b7050f)

**Comment by Night-stars-1** [comment]
> 请问青龙面板订阅管理中，拉取脚本，但在脚本管理当中并没有config.yaml文件，我需要怎么做 ![image](https://user-images.githubusercontent.com/120441658/282636848-4e7bcceb-fd01-4f5a-a9a4-57c4c5b7050f.png)

运行一次

**Comment by Tianqiwangdie** [comment]
> > 请问青龙面板订阅管理中，拉取脚本，但在脚本管理当中并没有config.yaml文件，我需要怎么做 ![image](https://user-images.githubusercontent.com/120441658/282636848-4e7bcceb-fd01-4f5a-a9a4-57c4c5b7050f.png)
> 
> 运行一次

![image](https://github.com/0-8-4/miui-auto-tasks/assets/120441658/d97616b7-8c8e-4a34-a607-440a23de9e4d)
![image](https://github.com/0-8-4/miui-auto-tasks/assets/120441658/ca4c46a0-be3f-4b33-b66d-ae2fa88ca531)
这是我的运行日志和依赖，麻烦请问我该如何操作

**Comment by Night-stars-1** [comment]
onepush
loguru>=0.7.2
pydantic>=2.4.2
httpx>=0.25.1
crypto==1.4.1
pyyaml>=6.0.1
tenacity>=8.2.3

依赖库

**Comment by for7GG** [comment]
> > > 请问青龙面板订阅管理中，拉取脚本，但在脚本管理当中并没有config.yaml文件，我需要怎么做 ![image](https://usercontent.githubfast.com/user-images/120441658/282636848-4e7bcceb-fd01-4f5a-a9a4-57c4c5b7050f.png)
> > 
> > 
> > 运行一次
> 
> ![image](https://usercontent.githubfast.com/user-images/120441658/282637428-d97616b7-8c8e-4a34-a607-440a23de9e4d.png) ![image](https://usercontent.githubfast.com/user-images/120441658/282637475-ca4c46a0-be3f-4b33-b66d-ae2fa88ca531.png) 这是我的运行日志和依赖，麻烦请问我该如何操作

按照提示安装依赖
![q](https://github.com/0-8-4/miui-auto-tasks/assets/10189846/b94fb137-f0d7-472a-843d-9e811af56aaa)

**Comment by Night-stars-1** [comment]
> ![image](https://user-images.githubusercontent.com/120441658/282637428-d97616b7-8c8e-4a34-a607-440a23de9e4d.png) ![image](https://user-images.githubusercontent.com/120441658/282637475-ca4c46a0-be3f-4b33-b66d-ae2fa88ca531.png) 这是我的运行日志和依赖，麻烦请问我该如何操作

onepush
loguru>=0.7.2
pydantic>=2.4.2
httpx>=0.25.1
crypto==1.4.1
pyyaml>=6.0.1
tenacity>=8.2.3

依赖库

**Comment by Karen-lai** [comment]
我也遇到了该问题

**Comment by Karen-lai** [comment]
删除青龙面板原订阅并删除文件，重新订阅后出现同样的问题，没有yaml，运行和图片输出错误提示相同。

**Comment by Higanoneko** [comment]
> 删除青龙面板原订阅并删除文件，重新订阅后出现同样的问题，没有yaml，运行和图片输出错误提示相同。

可以截个图看看吗

**Comment by Karen-lai** [comment]
<img width="705" alt="螢幕截圖 2023-11-14 下午8 05 02" src="https://github.com/0-8-4/miui-auto-tasks/assets/101018638/55de247a-9711-4b3f-b253-4147d1c0dabc">


> > 删除青龙面板原订阅并删除文件，重新订阅后出现同样的问题，没有yaml，运行和图片输出错误提示相同。
> 
> 可以截个图看看吗

**Comment by Karen-lai** [comment]
经过与上一个版本对比，更新后青龙面板添加订阅缺少部分文件，比如config.yaml，经过下载添加替换后即可正常运行。但是依然无法通过签到人机验证。
