### ISSUE TITLE
[Bug] 青龙2.10.13依赖装不上

### ISSUE THREAD

**Issue by mmeiwenlong** [0-8-4/miui-auto-tasks#176]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1最新

### Bug Found in Environment

Other

### Bug Found in Python Version

3.8

### Describe the Bug

开始安装依赖 orjson，开始时间 2023/11/19 上午10:02:18

Collecting orjson

  Using cached orjson-3.9.10.tar.gz (5.4 MB)

  Installing build dependencies: started

  Installing build dependencies: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-uyviiysb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=1,<2'
       cwd: None
  Complete output (56 lines):
  Collecting maturin<2,>=1
    Using cached maturin-1.3.2.tar.gz (176 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting tomli>=1.1.0; python_version < "3.11"
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Building wheels for collected packages: maturin
    Building wheel for maturin (PEP 517): started
    Building wheel for maturin (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pep517/_in_process.py build_wheel /tmp/tmpuipv5ler
         cwd: /tmp/pip-install-09ra4vej/maturin
    Complete output (35 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-cpython-38
    creating build/lib.linux-x86_64-cpython-38/maturin
    copying maturin/__main__.py -> build/lib.linux-x86_64-cpython-38/maturin
    copying maturin/import_hook.py -> build/lib.linux-x86_64-cpython-38/maturin
    copying maturin/__init__.py -> build/lib.linux-x86_64-cpython-38/maturin
    running egg_info
    creating maturin.egg-info
    writing maturin.egg-info/PKG-INFO
    writing dependency_links to maturin.egg-info/dependency_links.txt
    writing requirements to maturin.egg-info/requires.txt
    writing top-level names to maturin.egg-info/top_level.txt
    writing manifest file 'maturin.egg-info/SOURCES.txt'
    reading manifest file 'maturin.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /tmp/pip-build-env-e4jr863p/overlay/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py:80: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
      corresp(dist, value, root_dir)
    warning: no files found matching '*.json' under directory 'src/python_interpreter'
    writing manifest file 'maturin.egg-info/SOURCES.txt'
    running build_ext
    running build_rust
    error: can't find Rust compiler
  
    If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
  
    To update pip, run:
  
        pip install --upgrade pip
  
    and then retry package installation.
  
    If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
    ----------------------------------------
    ERROR: Failed building wheel for maturin
  Failed to build maturin
  ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-uyviiysb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=1,<2' Check the logs for full command output.

依赖安装失败，结束时间 2023/11/19 上午10:02:24，耗时 6.119 秒

### MIUITask Log

开始安装依赖 orjson，开始时间 2023/11/19 上午10:02:18

Collecting orjson

  Using cached orjson-3.9.10.tar.gz (5.4 MB)

  Installing build dependencies: started

  Installing build dependencies: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-uyviiysb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=1,<2'
       cwd: None
  Complete output (56 lines):
  Collecting maturin<2,>=1
    Using cached maturin-1.3.2.tar.gz (176 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting tomli>=1.1.0; python_version < "3.11"
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Building wheels for collected packages: maturin
    Building wheel for maturin (PEP 517): started
    Building wheel for maturin (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pep517/_in_process.py build_wheel /tmp/tmpuipv5ler
         cwd: /tmp/pip-install-09ra4vej/maturin
    Complete output (35 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-cpython-38
    creating build/lib.linux-x86_64-cpython-38/maturin
    copying maturin/__main__.py -> build/lib.linux-x86_64-cpython-38/maturin
    copying maturin/import_hook.py -> build/lib.linux-x86_64-cpython-38/maturin
    copying maturin/__init__.py -> build/lib.linux-x86_64-cpython-38/maturin
    running egg_info
    creating maturin.egg-info
    writing maturin.egg-info/PKG-INFO
    writing dependency_links to maturin.egg-info/dependency_links.txt
    writing requirements to maturin.egg-info/requires.txt
    writing top-level names to maturin.egg-info/top_level.txt
    writing manifest file 'maturin.egg-info/SOURCES.txt'
    reading manifest file 'maturin.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /tmp/pip-build-env-e4jr863p/overlay/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py:80: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
      corresp(dist, value, root_dir)
    warning: no files found matching '*.json' under directory 'src/python_interpreter'
    writing manifest file 'maturin.egg-info/SOURCES.txt'
    running build_ext
    running build_rust
    error: can't find Rust compiler
  
    If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
  
    To update pip, run:
  
        pip install --upgrade pip
  
    and then retry package installation.
  
    If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
    ----------------------------------------
    ERROR: Failed building wheel for maturin
  Failed to build maturin
  ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-uyviiysb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=1,<2' Check the logs for full command output.

依赖安装失败，结束时间 2023/11/19 上午10:02:24，耗时 6.119 秒

### Screenshots

![QQ截图20231119100554](https://github.com/0-8-4/miui-auto-tasks/assets/44661424/1155c3f4-f09f-436a-96dc-206d810c686b)

**Comment by HelloKitty2012** [comment]
orjson我也装不上

**Comment by Night-stars-1** [comment]
青龙升级到最新版

**Comment by BA7JCM** [comment]
先更新pip，
```shell
pip install pip -U
```
看提示说是pip太老了，然后还要装个Rust，
```shell
apk add rust
```
试下

**Comment by Golven-8964** [comment]
日志 - cryptography
开始安装依赖 cryptography，开始时间 2023/11/21 下午9:24:08
Collecting cryptography
  Using cached cryptography-41.0.5.tar.gz (630 kB)
  Installing build dependencies: started
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached cffi-1.16.0-cp38-cp38-linux_armv7l.whl
Collecting pycparser (from cffi>=1.12->cryptography)
  Building wheel for cryptography (pyproject.toml): started
  Building wheel for cryptography (pyproject.toml): finished with status 'error'
Failed to build cryptography
依赖安装失败，结束时间 2023/11/21 下午9:25:10，耗时 62.372 秒
有没有大佬知道怎么解决啊？
![屏幕截图 2023-11-21 212959](https://github.com/0-8-4/miui-auto-tasks/assets/71271253/fab5a45a-ebbf-4bb0-b5ab-fe48d2941595)

**Comment by Golven-8964** [comment]
开始安装依赖 cryptography，开始时间 2023/11/22 下午4:38:54
Collecting cryptography
  Using cached cryptography-41.0.5.tar.gz (630 kB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> [70 lines of output]
      Collecting setuptools>=61.0.0
        WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0xb54252c8>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/bb/e1/ed2dd0850446b8697ad28d118df885ad04140c64ace06c4bd559f7c8a94f/setuptools-69.0.2-py3-none-any.whl.metadata
        WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0xb5425400>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/bb/e1/ed2dd0850446b8697ad28d118df885ad04140c64ace06c4bd559f7c8a94f/setuptools-69.0.2-py3-none-any.whl.metadata
        Downloading setuptools-69.0.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Using cached wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
      Collecting cffi>=1.12
        Using cached cffi-1.16.0-cp38-cp38-linux_armv7l.whl
      Collecting setuptools-rust>=0.11.4
        Using cached setuptools_rust-1.8.1-py3-none-any.whl.metadata (9.4 kB)
      Collecting pycparser (from cffi>=1.12)
        Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
      Collecting semantic-version<3,>=2.8.2 (from setuptools-rust>=0.11.4)
        Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
      Collecting tomli>=1.2.1 (from setuptools-rust>=0.11.4)
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Downloading setuptools-69.0.2-py3-none-any.whl (819 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸         655.4/819.5 kB 5.2 kB/s eta 0:00:32
      ERROR: Exception:
      Traceback (most recent call last):
        File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
          yield
        File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
          data = self._fp_read(amt) if not fp_closed else b""
        File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
          return self._fp.read(amt) if amt is not None else self._fp.read()
        File "/usr/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
          data: bytes = self.__fp.read(amt)
        File "/usr/lib/python3.8/http/client.py", line 455, in read
          n = self.readinto(b)
        File "/usr/lib/python3.8/http/client.py", line 499, in readinto
          n = self.fp.readinto(b)
        File "/usr/lib/python3.8/socket.py", line 669, in readinto
          return self._sock.recv_into(b)
        File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
          return self.read(nbytes, buffer)
        File "/usr/lib/python3.8/ssl.py", line 1099, in read
          return self._sslobj.read(len, buffer)
      socket.timeout: The read operation timed out
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
          status = run_func(*args)
        File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
          return func(self, options, args)
        File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 377, in run
          requirement_set = resolver.resolve(
        File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
          self.factory.preparer.prepare_linked_requirements_more(reqs)
        File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 552, in prepare_linked_requirements_more
          self._complete_partial_requirements(
        File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 467, in _complete_partial_requirements
          for link, (filepath, _) in batch_download:
        File "/usr/lib/python3.8/site-packages/pip/_internal/network/download.py", line 183, in __call__
          for chunk in chunks:
        File "/usr/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
          for chunk in iterable:
        File "/usr/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
          for chunk in response.raw.stream(
        File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
          data = self.read(amt=amt, decode_content=decode_content)
        File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
          raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
        File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
          raise ReadTimeoutError(self._pool, None, "Read timed out.")
      pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
依赖安装失败，结束时间 2023/11/22 下午4:42:39，耗时 224.611 秒
![屏幕截图 2023-11-22 164435](https://github.com/0-8-4/miui-auto-tasks/assets/71271253/6b390f93-40e2-4fa7-bb3e-1ca28002c497)

**Comment by crossgg** [comment]
用qinglong:debian

**Comment by Night-stars-1** [comment]
该依赖已移除
