### ISSUE TITLE
[Bug] 缺少`apscheduler`依赖项

### ISSUE THREAD

**Issue by JaHIY** [0-8-4/miui-auto-tasks#182]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.2

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.9

### Describe the Bug

docker版本中缺少依赖`apscheduler`，应该是没有加进`pdm`里面吧……
建议运行
```
pdm add apscheduler
```
将`apscheduler`加入依赖项。

### MIUITask Log

```
$ docker exec -it 809 sh
/srv # python ./miuitask.py
Traceback (most recent call last):
  File "/srv/./miuitask.py", line 6, in <module>
    from apscheduler.schedulers.asyncio import AsyncIOScheduler
ModuleNotFoundError: No module named 'apscheduler'
```

**Comment by oubeichen** [comment]
另外 apscheduler 里面使用时区的 tzdata 的依赖也有点问题
```python
Traceback (most recent call last):
  File "zoneinfo/_common.py", line 12, in load_tzdata
  File "importlib/resources/_common.py", line 22, in files
  File "importlib/resources/_common.py", line 53, in get_package
  File "importlib/resources/_common.py", line 44, in resolve
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "miuitask.py", line 47, in <module>
  File "apscheduler/schedulers/base.py", line 97, in __init__
  File "apscheduler/schedulers/base.py", line 141, in configure
  File "apscheduler/schedulers/asyncio.py", line 46, in _configure
  File "apscheduler/schedulers/base.py", line 711, in _configure
  File "tzlocal/unix.py", line 219, in get_localzone
  File "tzlocal/unix.py", line 196, in _get_localzone
  File "zoneinfo/_common.py", line 24, in load_tzdata
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Asia/Shanghai'
```

**Comment by ZYMirror** [comment]
pip自己装一下咯

**Comment by Golven-8964** [comment]
![屏幕截图 2023-11-21 195928](https://github.com/0-8-4/miui-auto-tasks/assets/71271253/b5957f1b-a203-4b2a-b8ab-d12027ea43ab)
不知道缺少了什么依赖有大佬有类似的问题吗？
