### ISSUE TITLE
[Bug] 签到任务不能正常执行

### ISSUE THREAD

**Issue by Carnivorec** [0-8-4/miui-auto-tasks#240]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.3-hotfix2

### Bug Found in Environment

Windows

### Bug Found in Python Version

3.12

### Describe the Bug

已经装了最新版本的Python和运行环境，旧版本可以运行，更新到1.7.3后不能正常运行。

15:43:23 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.3
15:43:23 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
15:43:23 - INFO  | system_info.system_info:25 - 操作系统平台: Windows-10-10.0.19045-SP0
15:43:23 - INFO  | system_info.system_info:26 - 操作系统版本: 10.0.19045
15:43:23 - INFO  | system_info.system_info:27 - 操作系统名称: Windows
15:43:23 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', 'WindowsPE')
15:43:23 - INFO  | system_info.system_info:29 - 操作系统类型: AMD64
15:43:23 - INFO  | system_info.system_info:30 - 处理器信息: Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
15:43:23 - INFO  | system_info.system_info:31 - Python 版本: 3.12.1 ('tags/v3.12.1:2305ca5', 'Dec  7 2023 22:03:25')
15:43:23 - INFO  | system_info.system_info:33 - 系统代理: {'http': 'http://127.0.0.1:7891', 'https': 'http://127.0.0.1:7891', 'ftp': 'http://127.0.0.1:7891'}
15:43:23 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
15:43:23 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
15:43:23 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
15:43:23 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
15:43:23 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
15:43:25 - INFO  | login.login:72 - Cookie有效，跳过登录
15:43:26 - INFO  | miuitask.main:33 - 开始执行抢先体验小米澎湃OS！任务
15:43:26 - ERROR | miuitask.main:41 - 未找到抢先体验小米澎湃OS！任务
15:43:26 - INFO  | miuitask.main:33 - 开始执行每日签到任务
Traceback (most recent call last):
  File "C:\Python_sign_in\miui-auto-tasks\miuitask.py", line 48, in <module>
    asyncio.run(main())
  File "C:\Users\LCX\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\LCX\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LCX\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python_sign_in\miui-auto-tasks\miuitask.py", line 36, in main
    token = await get_token(cookies["cUserId"]) if task_obj == CheckIn else None
                            ~~~~~~~^^^^^^^^^^^
KeyError: 'cUserId'

### MIUITask Log

15:43:23 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.3
15:43:23 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
15:43:23 - INFO  | system_info.system_info:25 - 操作系统平台: Windows-10-10.0.19045-SP0
15:43:23 - INFO  | system_info.system_info:26 - 操作系统版本: 10.0.19045
15:43:23 - INFO  | system_info.system_info:27 - 操作系统名称: Windows
15:43:23 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', 'WindowsPE')
15:43:23 - INFO  | system_info.system_info:29 - 操作系统类型: AMD64
15:43:23 - INFO  | system_info.system_info:30 - 处理器信息: Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
15:43:23 - INFO  | system_info.system_info:31 - Python 版本: 3.12.1 ('tags/v3.12.1:2305ca5', 'Dec  7 2023 22:03:25')
15:43:23 - INFO  | system_info.system_info:33 - 系统代理: {'http': 'http://127.0.0.1:7891', 'https': 'http://127.0.0.1:7891', 'ftp': 'http://127.0.0.1:7891'}
15:43:23 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
15:43:23 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
15:43:23 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
15:43:23 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
15:43:23 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
15:43:25 - DEBUG | sign.check_daily_tasks:46 - {"time":0,"message":"success","entity":[{"head":{"img":"https://cdn.cnbj1.fds.api.mi-img.com/vipmlmodel/community_grow_up_level_icon/Color_48_2.png?GalaxyAccessKeyId\u003d5151729087601\u0026Expires\u003d9223372036854775807\u0026Signature\u003dVEgiVLyJCzy/ukW1fijqbM6GdXI\u003d","showType":1,"title":"2段 初级成员","jumpText":"","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/growth?skipLocal\u003dtrue","desc":"社区成长等级"},"cakeType":1},{"head":{"img":"https://cdn.cnbj1.fds.api.mi-img.com/vipmlmodel/icons/badge/1/社区勋章_60s.png?GalaxyAccessKeyId\u003dAKU25VNGWI6E4RUEAW\u0026Expires\u003d9223372036854775807\u0026Signature\u003dUId7rM4TsrONiivzGigL4KJYPi0\u003d","showType":1,"title":"全新升级","jumpText":"","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/badge?skipLocal\u003dtrue","desc":"社区勋章"},"cakeType":1},{"head":{"title":"每日任务","jumpText":"查看成长值规则","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/growthRules"},"data":[{"secondTitle":"火爆","showType":1,"title":"抢先体验小米澎湃OS！","jumpText":"去参加","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/blindBox/signUp?skipLocal\u003dtrue\u0026activityKey\u003dHyper2023\u0026isOnline\u003d1","desc":"火热进行中"},{"showType":1,"title":"每日签到","jumpText":"","jumpUrl":"","desc":"签到奖励随机，以实际获得为准"},{"showType":1,"title":"浏览帖子超过10秒","jumpText":"去浏览","jumpUrl":"mio://vipaccount.miui.com/main?tab\u003dmio\u0026sub_tab\u003drecommend","desc":"每次成长值+1，每日上限1分"}],"cakeType":2},{"head":{"title":"新手任务","jumpUrl":""},"data":[{"showType":0,"title":"首次完善个人资料","jumpText":"已完成","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/personalInfo","desc":"成长值+10，仅限首次"},{"showType":0,"title":"首次完成实名认证","jumpText":"已完成","jumpUrl":"https://certify.mipay.com/","desc":"成长值+10，仅限首次"}],"cakeType":2},{"head":{"title":"其他任务","jumpText":"更多任务","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/newshop/gold"},"data":[{"showType":1,"title":"参与拔萝卜获得奖励","jumpText":"去看看","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/arrive","desc":"以活动页面为准"}],"cakeType":2}],"status":200}
15:43:25 - INFO  | login.login:72 - Cookie有效，跳过登录
15:43:26 - DEBUG | sign.check_daily_tasks:46 - {"time":0,"message":"success","entity":[{"head":{"img":"https://cdn.cnbj1.fds.api.mi-img.com/vipmlmodel/community_grow_up_level_icon/Color_48_2.png?GalaxyAccessKeyId\u003d5151729087601\u0026Expires\u003d9223372036854775807\u0026Signature\u003dVEgiVLyJCzy/ukW1fijqbM6GdXI\u003d","showType":1,"title":"2段 初级成员","jumpText":"","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/growth?skipLocal\u003dtrue","desc":"社区成长等级"},"cakeType":1},{"head":{"img":"https://cdn.cnbj1.fds.api.mi-img.com/vipmlmodel/icons/badge/1/社区勋章_60s.png?GalaxyAccessKeyId\u003dAKU25VNGWI6E4RUEAW\u0026Expires\u003d9223372036854775807\u0026Signature\u003dUId7rM4TsrONiivzGigL4KJYPi0\u003d","showType":1,"title":"全新升级","jumpText":"","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/badge?skipLocal\u003dtrue","desc":"社区勋章"},"cakeType":1},{"head":{"title":"每日任务","jumpText":"查看成长值规则","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/growthRules"},"data":[{"secondTitle":"火爆","showType":1,"title":"抢先体验小米澎湃OS！","jumpText":"去参加","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/blindBox/signUp?skipLocal\u003dtrue\u0026activityKey\u003dHyper2023\u0026isOnline\u003d1","desc":"火热进行中"},{"showType":1,"title":"每日签到","jumpText":"","jumpUrl":"","desc":"签到奖励随机，以实际获得为准"},{"showType":1,"title":"浏览帖子超过10秒","jumpText":"去浏览","jumpUrl":"mio://vipaccount.miui.com/main?tab\u003dmio\u0026sub_tab\u003drecommend","desc":"每次成长值+1，每日上限1分"}],"cakeType":2},{"head":{"title":"新手任务","jumpUrl":""},"data":[{"showType":0,"title":"首次完善个人资料","jumpText":"已完成","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/personalInfo","desc":"成长值+10，仅限首次"},{"showType":0,"title":"首次完成实名认证","jumpText":"已完成","jumpUrl":"https://certify.mipay.com/","desc":"成长值+10，仅限首次"}],"cakeType":2},{"head":{"title":"其他任务","jumpText":"更多任务","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/newshop/gold"},"data":[{"showType":1,"title":"参与拔萝卜获得奖励","jumpText":"去看看","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/arrive","desc":"以活动页面为准"}],"cakeType":2}],"status":200}
15:43:26 - INFO  | miuitask.main:33 - 开始执行抢先体验小米澎湃OS！任务
15:43:26 - ERROR | miuitask.main:41 - 未找到抢先体验小米澎湃OS！任务
15:43:26 - INFO  | miuitask.main:33 - 开始执行每日签到任务


### MIUITask Config

```shell
preference:
    geetest_url: ''
    geetest_params: {}
    geetest_data: {}
accounts:
-   uid: ''
    password: 
    cookies:
    user_agent: Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko)
        Version/4.0 Chrome/116.0.0.0 Safari/537.36
    CheckIn: true
    BrowseUserPage: true
    BrowsePost: true
    ThumbUp: true
    BrowseSpecialPage: true
    BoardFollow: true
    CarrotPull: true
ONEPUSH:
    notifier: ''
    params:
        title: ''
        markdown: false
        token: ''
        userid: ''
```


### Screenshots

![image](https://github.com/0-8-4/miui-auto-tasks/assets/89299632/659ff6a5-26b6-4b19-8f26-50673b7b824c)

**Comment by Night-stars-1** [comment]
请正确填写配置
https://github.com/0-8-4/miui-auto-tasks/wiki

**Comment by Carnivorec** [comment]
配置应该没问题，没有报错，我把uid，password:，cookies:里面的值删了再发上来的。
