### ISSUE TITLE
用青龙提示这样 3个运行库都装了

### ISSUE THREAD

**Issue by lfsatan** [0-8-4/miui-auto-tasks#97]
Traceback (most recent call last):
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 11, in <module>
    from utils.utils import system_info, get_config, w_log, s_log, check_config, format_config, random_sleep, \
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 9, in <module>
    from onepush import notify
ModuleNotFoundError: No module named 'onepush'
![Screenshot_2023-04-15-07-41-15-601_mark via](https://user-images.githubusercontent.com/17214309/232171107-8f5d0f58-86db-4fd2-8fa9-6e479b80b23a.jpg)

**Comment by lfsatan** [comment]
解决了 少了个onepush
